/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ICustomFullscreenExpand: typeof import('~icons/custom/fullscreen-expand')['default']
    ICustomFullscreenShrink: typeof import('~icons/custom/fullscreen-shrink')['default']
    PlatformPickerDialog: typeof import('./src/components/platform-picker-dialog/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
